### ISSUE TITLE
How would I add a bad guy?

### ISSUE THREAD

**Issue by HardingRU** [HardingRU/Number-Punchers#1]
What you are trying to do:
- Trying to figure out adding logic for an enemy in my project (Number Punchers).  I can't figure out how I would get an enemy to move at random intervals in the game, without using an infinite while loop...

Detailed description of the bug or error
- Not a bug or error, need help with the logic

Relevant code/files/errors, screenshots
- NA

Technologies being used/attempted
- JavaScript...

Documentation you have looked at: 
- I have tried googling a few things, but this is a rare example of struggling to even know what I'd google

Steps you have taken to solve the problem
- Thought long and hard about it...

@johnrbell

**Comment by jsm13** [comment]
Check out [setInterval](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval#Examples). You don't want an infinite loop because then your event listeners won't be able to run. `setInterval` will repeatedly call a function at a specified interval so could do something like `setInterval(moveMonster, 500)` which would call a `moveMonster` function every half second.
